version: '3.1'

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/gateway-augusto/gateway-augusto.Dockerfile
    environment:
      - VISION_PORT=10006
    volumes:
      - .ssl-core:/tmp/.ssl-core
    ports:
      - 50051:50051
      - "224.5.23.2:10006:10006/udp"
      - "224.5.23.2:10010:10010/udp"
      - "224.5.23.1:11003:11003/udp"

  perception-ms:
    container_name: perception-ms
    image: robocin/perception-brutus:manual-c7208b
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway

  referee-ms:
    container_name: referee-ms
    image: robocin/referee-daronco:manual-419128
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms

  playback-db:
    container_name: playback-db
    image: "redis:latest"

  playback-ms:
    container_name: playback-ms
    build:
      context: .
      dockerfile: playback-ms/playback-caze/playback-caze.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - referee-ms
      - playback-db

  player-bff:
    container_name: player-bff
    build:
      context: .
      dockerfile: player-bff/player-sonson/player-sonson.Dockerfile
    ports:
      - 4040:4040
    depends_on:
      - gateway
      - playback-ms

  player-mfe:
    build:
      context: .
      dockerfile: player-mfe/Dockerfile
      args:
        - SOURCE_DIRECTORY=player-mfe
    command: ["-g", "daemon off;"]
    ports:
      - 3031:80
    depends_on:
      - player-bff

  viewer-mfe:
    build:
      context: .
      dockerfile: viewer-mfe/Dockerfile
      args:
        - SOURCE_DIRECTORY=viewer-mfe
    command: ["-g", "daemon off;"]
    ports:
      - 3032:80

  app-shell:
    build:
      context: .
      dockerfile: app-shell/Dockerfile
      args:
        - SOURCE_DIRECTORY=app-shell
    command: ["-g", "daemon off;"]
    ports:
      - 3030:80

  redis-db:
    container_name: redis-db
    image: "redis:latest"
  
  metrics-db:
    image: influxdb:latest
    container_name: metrics-db
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ssl-core
      DOCKER_INFLUXDB_INIT_PASSWORD: ssl-core
      DOCKER_INFLUXDB_INIT_ORG: ssl-core
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_RETENTION: 6h
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: metrics
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=ssl-core
      - GF_SECURITY_ADMIN_PASSWORD=ssl-core
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - metrics-db

  metrics-ms:
    container_name: metrics-ms
    build:
      context: .
      dockerfile: metrics-ms/metrics-sherlock/metrics-sherlock.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - playback-ms
      - metrics-db
      - grafana

volumes:
  .ssl-core:
  influxdb-data:
  grafana-data: