services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/gateway-augusto/gateway-augusto.Dockerfile
    environment:
      - VISION_PORT=10006
      - GC_PORT=10003
    volumes:
      - .ssl-core:/tmp/.ssl-core
    network_mode: host

  game-controller:
    container_name: game-controller
    image: robocupssl/ssl-game-controller:3.9.0
    command:
      - "-visionAddress"
      - "224.5.23.2:10006"
      - "-trackerAddress"
      - "224.5.23.2:10010"
      - "-publishAddress"
      - "224.5.23.1:10003"
      - "-address"
      - ":8081"
    restart: unless-stopped
    ports:
      - 8081/tcp
      - 8081:8081
    logging:
      driver: none
    network_mode: host

  perception-ms:
    container_name: perception-ms
    build:
      context: .
      dockerfile: perception-ms/perception-brutus/perception-brutus.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway
    network_mode: host

  ssl-vision-client:
    container_name: ssl-vision-client
    image: robocupssl/ssl-vision-client:1.7.3
    command:
      - "-visionAddress"
      - "224.5.23.2:10006"
    restart: unless-stopped
    ports:
      - 8082/tcp
      - 8082:8082
    logging:
      driver: none
    network_mode: host

  referee-ms:
    container_name: referee-ms
    image: robocin/referee-daronco:manual-419128
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms
    network_mode: host

  playback-db:
    container_name: playback-db
    image: "redis:latest"
    network_mode: host

  playback-ms:
    container_name: playback-ms
    build:
      context: .
      dockerfile: playback-ms/playback-caze/playback-caze.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - referee-ms
      - playback-db
    network_mode: host
    extra_hosts:
      - "playback-db:127.0.0.1"

  player-bff:
    container_name: player-bff
    build:
      context: .
      dockerfile: player-bff/player-sonson/player-sonson.Dockerfile
    depends_on:
      - gateway
      - playback-ms
    network_mode: host
    extra_hosts:
      - "gateway:127.0.0.1"

  player-mfe:
    build:
      context: .
      dockerfile: player-mfe/Dockerfile
      args:
        - SOURCE_DIRECTORY=player-mfe
    command: [ "-g", "daemon off;" ]
    depends_on:
      - player-bff
    network_mode: host

  viewer-mfe:
    build:
      context: .
      dockerfile: viewer-mfe/Dockerfile
      args:
        - SOURCE_DIRECTORY=viewer-mfe
    command: [ "-g", "daemon off;" ]
    network_mode: host

  app-shell:
    build:
      context: .
      dockerfile: app-shell/Dockerfile
      args:
        - SOURCE_DIRECTORY=app-shell
    command: [ "-g", "daemon off;" ]
    network_mode: host

  decision-ms:
    container_name: decision-ms
    build:
      context: .
      dockerfile: decision-ms/decision-guardiola/decision-guardiola.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms
      - referee-ms

  behavior-ms:
    container_name: behavior-ms
    build:
      context: .
      dockerfile: behavior-ms/behavior-bruxo/behavior-bruxo.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms
      - decision-ms

  navigation-ms:
    container_name: navigation-ms
    build:
      context: .
      dockerfile: navigation-ms/navigation-luffy/navigation-luffy.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms
      - behavior-ms

  communication-ms:
    container_name: communication-ms
    build:
      context: .
      dockerfile: communication-ms/communication-jaiminho/communication-jaiminho.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway
    network_mode: "host"
    depends_on:
      - perception-ms
      - navigation-ms

volumes:
  .ssl-core:
