match:
  path: /watch
  label: Assistir
  icon: radio
  rows: 12
  cols: 1
  fragments:
    player:
      url: http://127.0.0.1:3032/viewer-mfe.js
      type: webcomponent
      metadata:
        tag: viewer-mfe
      rows:
        start: 1
        end: 11
      cols:
        start: 1
        end: 2
    parameters:
      url: http://127.0.0.1:3031/player-mfe.js
      type: webcomponent
      metadata:
        tag: player-mfe
      rows:
        start: 11
        end: 13
      cols:
        start: 1
        end: 2

parameters:
  path: /parameters
  label: Par√¢metros
  icon: radio # change later
  rows: 1
  cols: 1
  fragments:
    player:
      url: http://127.0.0.1:3033/params-mfe.js
      type: webcomponent
      metadata:
        tag: params-mfe
      rows:
        start: 1
        end: 2
      cols:
        start: 1
        end: 2