match:
  path: /watch
  label: Assistir
  icon: radio
  rows: 12
  cols: 5
  fragments:
    viewer:
      url: http://127.0.0.1:3032/viewer-mfe.js
      type: webcomponent
      metadata:
        tag: viewer-mfe
      rows:
        start: 1
        end: 11
      cols:
        start: 1
        end: 5
    player:
      url: http://127.0.0.1:3031/player-mfe.js
      type: webcomponent
      metadata:
        tag: player-mfe
      rows:
        start: 11
        end: 13
      cols:
        start: 1
        end: 5
    scoreboard:
      url: http://127.0.0.1:3033/scoreboard-mfe.js
      type: webcomponent
      metadata:
        tag: scoreboard-mfe
      rows:
        start: 1
        end: 13
      cols:
        start: 5
        end: 6
